---
title: "ClimWin_Covariate"
author: "Kai Frazer"
format: html
editor: visual
---

#### References

#### AI Disclosure

Claude chat that first suggested climwin as a package to explore, as well as some introductory code for using it: <https://claude.ai/share/d8438437-ed0e-4b85-9ab0-8306300d8731>

## Packages & Data

```{r}
#| label: libraries

library(pacman)
p_load(lme4, climwin, terra)
```

```{r}
#| label: data for model
# note: duplicate of methods from Frequentist_Null.qmd

matrices <- readRDS('/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/GoMBlueCrabs/ModelReadyData/modelready_matrices.rds')

# extract data i want
crab <- matrices[["crab_abun"]]
points <- matrices[["points"]]
pop <- matrices[["pop"]]

# function to translate datat to long form
make.long <- function(wide, flatornot, colname) {
  
  if (flatornot == "not") { # for timev varying data
    long <- as.data.frame(wide) %>% mutate(cell_id = rownames(wide)) %>%
      pivot_longer(-cell_id, names_to = "year", values_to = colname)}
  
  if (flatornot == "flat") { # for static data
    long <- as.data.frame(wide)
    long <- mutate(long, cell_id = rownames(long))}
  
  return(long)
}

# make everything long
crab_long <- make.long(crab, "not", "count")
points_long <- make.long(points, "flat", "")
pop_long <- make.long(pop, "flat", "")

# join data
data <- crab_long %>%
  left_join(points_long, by = "cell_id") %>%
  left_join(pop_long, by = "cell_id") %>% rename("pop" = "wide")
```

```{r}
#| label: climate data for climwin

## oisst code from Covariate_Construction.qmd

oisst_daily <- readRDS('/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/Data/oisst_1982_2026.rds') %>% 
  mutate(date_time = ymd_hms(time), date = date(date_time), 
         year = year(date), month = month(date), 
         yearmon = as.yearmon(date),
         season = factor(case_when(month %in% c(12,1,2) ~ "Winter",
                            month %in% c(3,4,5) ~ "Spring",
                            month %in% c(6,7,8) ~ "Summer",
                            month %in% c(9,10,11) ~ "Fall"))) %>%
  select(longitude, latitude, date_time, date, year, yearmon, month, season, sst) %>%
  mutate(longitude = case_when(as.numeric(longitude) < 0 ~ longitude,
                               as.numeric(longitude) > 0 ~ as.numeric(longitude) - 360))

oisst_daily_nona <- na.omit(oisst_daily) # now the monthly data shouldn't have NAs

oisst_monthly_nona <- oisst_daily_nona %>%
  group_by(longitude, latitude, yearmon, year, season, month) %>%
  summarize(monthly_sst = mean(sst), monthly_min = min(sst), monthly_max = max(sst)) %>%
  mutate(longitude = case_when(as.numeric(longitude) < 0 ~ longitude,
                               as.numeric(longitude) > 0 ~ as.numeric(longitude) - 360))

oisst_month_points <- right_join(oisst_monthly_nona, 
                                   points_long, by = c("longitude", "latitude")) %>% 
  mutate(date = as.Date(yearmon)) %>% ungroup() %>% select(date, monthly_sst, cell_id)
```

```{r}
#| label: bio data for climwin

crab_month <- readRDS("ModelReadyData/crab[i,m,y].rds")
crab_month_long <- as.data.frame(crab_month) %>% mutate(lonlat = rownames(crab_month)) %>%
      pivot_longer(-lonlat, names_to = "yearmon", values_to = "abun") %>%
      separate(lonlat, into = c("longitude", "latitude"), sep="_") %>% 
  mutate(longitude = as.double(longitude), latitude = as.double(latitude)) %>%
  left_join(points_long) %>%
  mutate(date = as.Date(as.yearmon(yearmon, format="%Y.%b"))) %>% select(date, abun, cell_id) %>%
  filter(date %in% unique(oisst_month_points$date))
```

## Null model

```{r}
#| label: reconstructing model from Frequentist_Covariate.qmd

# climwin can only take lm, glm, lmer, glmer
# best model was glmmTMB(count ~ scale(summer_mean) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = data) with an AIC of 1302; let's see how close we can get to that

baseline <- glmer.nb(count ~ (1|year), data=data)
```

## Search for lag window

```{r}
#| label: search

# claude code
lag_search <- slidingwin(
  xvar = list(winter = climate_data$winter_mean),
  cdate = climate_data$year,
  bdate = bio_data$date,
  baseline = baseline,
  range = c(48, 0),       # 0 to 4 years back, in months
  type = "relative",
  stat = c("mean", "min"),         # test both summary stats you care about
  func = c("lin", "quad"),         # allow for a non-monotonic lag-response shape
  cinterval = "month"
)

```
