---
title: "ClimWin_NewModelandPrediction"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

#### AI disclosure

Claude chat helping me make simple ggplot code: <https://claude.ai/share/dfeabd60-5816-4fc8-b375-edba04c53194>

## Packages:

```{r}
#| label: libraries

library(pacman)
p_load(dplyr, tidyr, glmmTMB, lubridate, zoo, ggplot2, terra, tidyterra)
```

```{r}
#| label: data and previous models

### data for null model

matrices <- readRDS('/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/GoMBlueCrabs/ModelReadyData/modelready_matrices.rds')

# extract data i want
crab <- matrices[["crab_abun"]]
points <- matrices[["points"]]
summer_mean <- matrices[["summer_mean"]]
pop <- matrices[["pop"]]

# function to translate datat to long form
make.long <- function(wide, flatornot, colname) {
  
  if (flatornot == "not") { # for timev varying data
    long <- as.data.frame(wide) %>% mutate(cell_id = rownames(wide)) %>%
      pivot_longer(-cell_id, names_to = "year", values_to = colname)}
  
  if (flatornot == "flat") { # for static data
    long <- as.data.frame(wide)
    long <- mutate(long, cell_id = rownames(long))}
  
  return(long)
}

# make everything long
crab_long <- make.long(crab, "not", "count")
points_long <- make.long(points, "flat", "")
summer_mean_long <- make.long(summer_mean, "not", "summer_mean")
pop_long <- make.long(pop, "flat", "")

# join data
data <- crab_long %>%
  left_join(points_long, by = "cell_id") %>%
  left_join(summer_mean_long, by = c("cell_id", "year")) %>%
  left_join(pop_long, by = "cell_id") %>% rename("pop" = "wide")

### null model

null <- glmmTMB(count ~ 1, ziformula = ~ pop + latitude, family = nbinom2(), data = data)

### previous best model

effect <- glmmTMB(count ~ scale(summer_mean) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = data)
```

## Data:

```{r}
#| label: bring in climwin analysis result

## climwin data

climwin <- readRDS("/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/slidingwin_search4_20260724.rds")

climwin_models <- climwin[[1]]$Dataset
climwin_topmod <- climwin[[1]]$BestModel
climwin_dat <- climwin[[1]]$BestModelData
```

```{r}
#| label: gather climate data for recreating climwin model in tmb

## get oisst data

# oisst code from Covariate_Construction.qmd
oisst_daily <- readRDS('/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/Data/oisst_1982_202603.rds') %>% 
  mutate(date_time = ymd_hms(time), date = date(date_time), 
         year = year(date), month = month(date), 
         yearmon = as.yearmon(date),
         season = factor(case_when(month %in% c(12,1,2) ~ "Winter",
                            month %in% c(3,4,5) ~ "Spring",
                            month %in% c(6,7,8) ~ "Summer",
                            month %in% c(9,10,11) ~ "Fall"))) %>%
  select(longitude, latitude, date_time, date, year, yearmon, month, season, sst) %>%
  mutate(longitude = case_when(as.numeric(longitude) < 0 ~ longitude,
                               as.numeric(longitude) > 0 ~ as.numeric(longitude) - 360))

oisst_daily_nona <- na.omit(oisst_daily) # now the monthly data shouldn't have NAs

oisst_monthly_nona <- oisst_daily_nona %>%
  group_by(longitude, latitude, yearmon, year, season, month) %>%
  summarize(monthly_sst = mean(sst), monthly_min = min(sst), monthly_max = max(sst)) %>%
  mutate(longitude = case_when(as.numeric(longitude) < 0 ~ longitude,
                               as.numeric(longitude) > 0 ~ as.numeric(longitude) - 360))

oisst_month_points <- right_join(oisst_monthly_nona, 
                                   points_long, by = c("longitude", "latitude")) %>% 
  mutate(date = as.Date(yearmon)) %>% ungroup() %>% select(date, monthly_sst, cell_id) # %>%
  # filter(year(date) != 2026) # I want 2026 now that I'm using both testing and training sets

climdat <- oisst_month_points

## create climdat with climwins

# 48 to 46 is the best for 4 years ago, 12 to 11 is the best for 1 year ago, 36 to 34 is the best for 3 years ago, 25 to 22 is the best for 2 years ago

climdat <- climdat %>% mutate(year = year(date), month = month(date)) %>%
  mutate(fouryearwin = NA, threeyearwin = NA, twoyearwin = NA, oneyearwin = NA) 
# establish columns for analysis

for(i in 1:nrow(climdat)) {
  if(climdat$year[i] >= 1986) { # 1986 points would use July to September of 1982, so that's our first year of available window analysis; can't calculate a window for years before 1987
    cellfilter <- filter(climdat, cell_id == climdat$cell_id[i])
    climdat$fouryearwin[i] <- filter(cellfilter, year == climdat$year[i] - 4,
                                     month %in% c("7", "8", "9")) %>%
      summarize(val = mean(monthly_sst))
    climdat$threeyearwin[i] <- filter(cellfilter, year == climdat$year[i] - 3,
                                     month %in% c("7", "8", "9")) %>%
      summarize(val = mean(monthly_sst))
    climdat$twoyearwin[i] <- filter(cellfilter, year == climdat$year[i] - 2,
                                     month %in% c("6", "7", "8", "9")) %>%
      summarize(val = mean(monthly_sst))
    climdat$oneyearwin[i] <- filter(cellfilter, year == climdat$year[i] - 1,
                                     month %in% c("6", "7")) %>%
      summarize(val = mean(monthly_sst))
    print(i)
  }
} 
```

```{r}
#| label: bring in biodat used to fit the climwin

crab_month <- readRDS("ModelReadyData/crab[i,m,y].rds")
crab_month_long <- as.data.frame(crab_month) %>% mutate(lonlat = rownames(crab_month)) %>%
      pivot_longer(-lonlat, names_to = "yearmon", values_to = "abun") %>%
      separate(lonlat, into = c("longitude", "latitude"), sep="_") %>% 
  mutate(longitude = as.double(longitude), latitude = as.double(latitude)) %>%
  left_join(points_long) %>%
  mutate(date = as.Date(as.yearmon(yearmon, format="%Y.%b"))) %>% select(date, abun, cell_id)
  # filter(date %in% unique(oisst_month_points$date)[49:533]) # , year(date) != 2026

# Find the last date with a crab observation
last_date <- max(filter(crab_month_long, abun > 0)$date)

# Filter to dates before the last observation
crab_month_long <- crab_month_long %>% filter(date <= last_date)

biodat <- crab_month_long
```

```{r}
#| label: combine climdat and biodat

## clean things up a bit and combine with biodat

climwindat <- left_join(climdat, biodat, by = c("cell_id", "date")) %>%
  na.omit() %>% # remove those first four years of data
  mutate(fouryearwin = as.numeric(fouryearwin), # these were outputted as lists so change
         threeyearwin = as.numeric(threeyearwin),
         twoyearwin = as.numeric(twoyearwin),
         oneyearwin = as.numeric(oneyearwin)) %>%
  group_by(cell_id, year) %>% summarize(abun = sum(abun), # get yearly values rather than mo
                                        fouryearwin = mean(fouryearwin),
                                        threeyearwin = mean(threeyearwin),
                                        twoyearwin = mean(twoyearwin),
                                        oneyearwin = mean(oneyearwin)) %>%
  left_join(pop_long, by = "cell_id") %>% rename("pop" = "wide") %>%
  left_join(points_long, by = "cell_id")

saveRDS(climwindat, '/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/GOMBlueCrabs/ModelReadyData/climwindat.rds')

# climwindat <- readRDS('/Users/kailafrazer/CloudStorage/OneDrive-USNH/Crab/GOMBlueCrabs/ModelReadyData/climwindat.rds')
```

## Full data models

```{r}
#| label: try different reconstructions of the climwin model

## this is the winner, as identified by climwin (yay!)
climwin4yr_tmb <- glmmTMB(abun ~ scale(fouryearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1274 with up to 2025, goes down to 1294 with 2026 included

climwin3yr_tmb <- glmmTMB(abun ~ scale(threeyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1281 -> 1304

climwin2yr_tmb <- glmmTMB(abun ~ scale(twoyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1291 -> 1312

climwin1yr_tmb <- glmmTMB(abun ~ scale(oneyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1304 -> 1326

## additions - opted not to build the poster from these because they aren't clearly represented in the climwin fig and they have negative responses to one year

climwin4and3yr_tmb <- glmmTMB(abun ~ scale(fouryearwin) + scale(threeyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1276

climwin4and2yr_tmb <- glmmTMB(abun ~ scale(fouryearwin) + scale(twoyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1272

climwin4and1yr_tmb <- glmmTMB(abun ~ scale(fouryearwin) + scale(oneyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1269

## interactions

climwin43yr_tmb <- glmmTMB(abun ~ scale(fouryearwin) * scale(threeyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1255

climwin42yr_tmb <- glmmTMB(abun ~ scale(fouryearwin) * scale(twoyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1271

climwin41yr_tmb <- glmmTMB(abun ~ scale(fouryearwin) * scale(oneyearwin) + (1|year), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = climwindat) # AIC 1268
```

```{r}
#| label: compare aic

AIC(climwin4yr_tmb) # 1274
AIC(climwin43yr_tmb) # 1255 HOWEVER the interaction is negative which makes less biological sense to me so i'm gonna roll with the 4yr model for the poster as i chew more on this
AIC(null) # 1756
AIC(effect) # 1302
```

```{r}
#| label: save model RDS files for access in EFI_Figs.qmd

saveRDS(climwin4yr_tmb, '/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/GOMBlueCrabs/ModelFiles/climwin4yr_tmb.rds')
saveRDS(null, '/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/GOMBlueCrabs/ModelFiles/null.rds')
saveRDS(effect, '/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/GOMBlueCrabs/ModelFiles/0yrsummer_tmb.rds')
saveRDS(climwindat, '/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Crab/GOMBlueCrabs/ModelFiles/climwindat_recreation.rds')
```

## Model with testing data

```{r}
#| label: re-fit model just on training data and plot full set of predictions

# try it with just recent years of data
# try <- filter(climwindat, abun > 0); min(try$year) # found 2006 to be the first year of data in this post-OISST start set with abundance
climwindat_recent <- climwindat %>% filter(year >= 2006) %>%
    mutate(year_factor = factor(year), year_numeric = as.numeric(year)) %>%
  mutate(test_train = case_when(year >= 2021 ~ "Project", year < 2021 ~ "Predict"))

# decide where to split testing from training
# ggplot(climwindat, aes(x = year, y = abun)) + geom_point() # sharp increase starts around 2020
train <- climwindat_recent %>% filter(year < 2021)

# train model
climwin4yr_tmb_train <- glmmTMB(abun ~ scale(fouryearwin) + scale(year_numeric) + (1|cell_id), ziformula = ~ scale(pop) + scale(latitude), family = nbinom2(), data = train) # adjusted to include year_numeric and instead of  because the non-trended random effect was resulting in predictions near zero for future years. process made me realize i need to rethink these parts of the model

# predict
pred <- predict(climwin4yr_tmb_train, newdata = na.omit(climwindat_recent), se.fit = T, type = "link") # allow extrapolation of year

preds_df <- cbind(as.numeric(pred$fit), as.numeric(pred$se.fit), na.omit(climwindat_recent)) %>%
  rename("pred_link" = "...1", "se_link" = "...2") %>%
  mutate(pred_resp = exp(pred_link),
           lower_resp = exp(pred_link - 1.96 * se_link), 
           upper_resp = exp(pred_link + 1.96 * se_link)) #%>% filter(year < 2026) #%>% # find upper/lower
    # mutate(covar_descaled = covar_seq * attr(scale(covar_vect), 'scaled:scale') +
    #                            attr(scale(covar_vect), 'scaled:center'))

preds_df_means <- preds_df %>% group_by(year) %>% 
  summarize(obs_mean = mean(abun), obs_upper = max(abun), obs_lower = min(abun),
            pred_mean = mean(pred_resp), pred_lower = min(pred_resp), pred_upper = max(pred_resp),
            lower_resp = mean(lower_resp), upper_resp = mean(upper_resp)) %>%
  mutate(test_train = case_when(year >= 2021 ~ "Project", year < 2021 ~ "Predict"))

# plot all points
ggplot(preds_df, aes(x = year)) + geom_jitter(aes(y = abun, color = "Actual")) +
  geom_jitter(aes(y = pred_resp, color = test_train), alpha = 0.5) + theme_classic() +
  scale_color_viridis_d()

# plot ranges and means
ggplot(preds_df_means, aes(x = year)) + 
  geom_ribbon(aes(ymin = obs_lower, ymax = obs_upper, fill = "Actual"), alpha = 0.3) +
  geom_line(aes(y = obs_mean, color = "Actual")) +
    geom_ribbon(aes(ymin = lower_resp, ymax = upper_resp, fill = test_train), alpha = 0.3) +
  geom_line(aes(y = pred_mean, color = test_train), alpha = 0.5) + theme_classic() +
  scale_color_viridis_d() + scale_fill_viridis_d()
  # so this isn't the uncertainty it's the range of values observed fr

# notes: on first attempt, the years in the testing data get functionally zero abundance (I think because the random effect was really controlling the abundance). When I remove the random effect, I get lower level abundance across the set

### claude update below, commented and updated by me

# smooth the bounds of the intervals but less so than geom_smooth would
preds_df_means_smooth <- preds_df_means %>%
  arrange(year) %>%
  mutate(
    resp_lower_smooth = predict(loess(lower_resp ~ year, data = ., span = 0.6)),
    resp_upper_smooth = predict(loess(upper_resp ~ year, data = ., span = 0.6)),
    obs_lower_smooth = predict(loess(obs_lower ~ year, data = ., span = 0.6)),
    obs_upper_smooth = predict(loess(obs_upper ~ year, data = ., span = 0.6))
  )

# fill missing test_train values
boundary_row <- preds_df_means_smooth %>%
  filter(year == max(year[test_train == "Predict"])) %>%
  mutate(test_train = "Project")

# data for plotting
plot_data <- bind_rows(preds_df_means_smooth, boundary_row) %>%
  arrange(year, test_train)

# updated plot, originally by me revised by Claude to have these smoother bounds
gg <- ggplot(plot_data, aes(x = year)) +
  geom_ribbon(aes(ymin = obs_lower_smooth, ymax = obs_upper_smooth, fill = "Observed", color = "Observed"), alpha = 0.2, lwd = 0.1) +
  geom_line(aes(y = obs_mean, color = "Observed")) +
  geom_ribbon(aes(ymin = resp_lower_smooth, ymax = resp_upper_smooth,
                   fill = test_train, group = test_train, color = test_train), alpha = 0.2, lwd = 0.1) +
  geom_line(aes(y = pred_mean, color = test_train, group = test_train),
           linetype = "dashed") +
  theme_classic() +
  scale_color_viridis_d("", option = "E", direction = -1) +
  scale_fill_viridis_d("", option = "E", direction = -1) + 
  labs(x = "Year", y = "Mean crab abundance")

ggsave(plot=gg, height = 2, width = 4, unit = "in", "/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Figs/obsvpredproj.png")
```

## Figs for EFI

```{r}
#| label: new oisst fig with lag

# create relevant grid
grid <- readRDS("ModelReadyData/grid.rds")
grid_poly <- readRDS("ModelReadyData/grid_poly.rds")

# prep for plot
rast <- grid
cells <- cellFromXY(grid, as.matrix(matrices[["points"]]))
values(rast) <- NA
covar <- climdat %>% group_by(cell_id, year) %>%
  summarize(fouryearwin = mean(as.numeric(fouryearwin))) %>% filter(year == 2023) %>%
  arrange(as.numeric(cell_id))
rast[cells] <- covar$fouryearwin

gg <- ggplot() + 
    geom_spatraster(data = rast) +
    geom_spatvector(data = land_outline, aes(color = "Coastline"), 
                  fill = "lightgray", alpha = 0.4, lwd = 0.1) +
    geom_spatvector(data = grid_poly, aes(color = "Study area\n> -46m"), 
                    fill = NA, lwd = 0.3, linetype = 5) + 
    scale_fill_viridis_c("2019 summer\nmean temp (°C)",
                       na.value = "white") +
    scale_color_viridis_d("Outlines", option = "H") +
    labs(x = "Latitude", y = "Longitude", title = "B. Mean 2019 summer temps (°C)") +
    coord_sf() +
    theme_classic()

ggsave(plot=gg, width = 5, height = 4, unit = "in", '/Users/kailafrazer/Library/CloudStorage/OneDrive-USNH/Figs/LagSummerTemp.png')
```
